name: Unit Tests
on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]
jobs:
    test_unit:
        name: Run Unit Tests
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - name: Prepare testing env
              uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 20
            - run: yarn install --frozen-lockfile
            - name: Run tests
              run: yarn run test:unit
            - name: Run lint
              run: yarn run lint